// Seed existing blogs into MongoDB
// Usage: node scripts/seed-blogs.js

require('dotenv').config();
const mongoose = require('mongoose');
const BlogSubmission = require('../models/BlogSubmission');
const Admin = require('../models/Admin');

const MONGODB_URI = process.env.MONGODB_URI || '';

// Existing blogs from blogs.js
const existingBlogs = [
  { id: 1, title: "Top 10 Social Engineering Red Flags in 2025", category: "awareness", date: "Nov 2025", readTime: "6 min", excerpt: "Learn to identify sophisticated social engineering attacks.", content: "As we move into late 2025, social engineering attacks continue to evolve with AI-enhanced targeting and deepfake technology becoming mainstream. The top 10 red flags include: 1) Unsolicited urgent requests creating artificial pressure, 2) Authority impersonation with perfect grammar (attackers now use AI), 3) Phishing emails with legitimate company logos and layouts, 4) Shortened URLs hiding malicious destinations, 5) Requests for sensitive information via email (legitimate companies never ask this), 6) CEO fraud targeting finance teams, 7) Shared Google Docs with unexpected access requests, 8) Calls claiming to be from IT support, 9) LinkedIn messages from 'recruiters' with suspicious links, 10) Package delivery notifications from unknown couriers. Statistics from November 2025 show a 34% increase in social engineering incidents compared to November 2024. Organizations should implement verification protocols: call back using known numbers, verify sender email domains carefully, and use security awareness training monthly. The average cost of a successful social engineering attack is $130,000 in recovery and lost data.", author: "Security Team", tags: ["social-eng", "phishing", "awareness"] },
  { id: 2, title: "Critical Infrastructure Protection", category: "threats", date: "Dec 2025", readTime: "8 min", excerpt: "Safeguarding power, telecom, financial systems from cyber threats.", content: "December 2025 marks a critical period for Critical Infrastructure (CII) protection as India's energy, telecom, financial, and water systems face unprecedented cyber threats. Recent incidents in Q3-Q4 2025 highlight vulnerabilities: several state power grids experienced reconnaissance attacks, and telecom networks reported DDoS attempts. India's NCIIPC (National Critical Information Infrastructure Protection Centre) has mandated compliance with IEC 62443 standards for all critical infrastructure operators. Key protection strategies for December 2025 onwards include: implementing Zero Trust Architecture with multi-factor authentication for all privileged accounts, deploying real-time network monitoring systems with 24/7 SOC oversight, maintaining air-gapped backup systems, and conducting quarterly penetration tests. Organizations must establish Incident Response plans with defined Recovery Time Objectives (RTO) of less than 2 hours for critical systems. The financial sector has already adopted blockchain-based authentication in some systems. Telecom operators are implementing quantum-resistant encryption pilots. Energy companies are segmenting SCADA networks from IT systems. India has also launched the 'Critical Infrastructure Resilience Initiative' in 2025 to provide resources and frameworks. Data from CERT-In shows 47% of reported incidents target critical infrastructure, making this a national priority.", author: "Infra Team", tags: ["cii", "defense", "policy"] },
  { id: 3, title: "Building Cyber Hygiene Routine", category: "awareness", date: "Oct 2025", readTime: "4 min", excerpt: "5 daily cybersecurity habits that protect your data.", content: "October 2025 cybersecurity research confirms that 91% of successful breaches occur due to poor hygiene practices rather than zero-day exploits. Building a daily cyber hygiene routine takes just 10 minutes but prevents over 90% of common attacks. The five essential practices are: (1) Update software and patches immediately - set OS updates to automatic; most breaches exploit known vulnerabilities patched months ago; (2) Use strong passwords - minimum 16 characters with upper, lower, numbers, and symbols; consider using a password manager like Bitwarden; (3) Enable Multi-Factor Authentication (MFA) on all critical accounts (email, banking, work) - in Oct 2025, MFA prevented 99.9% of account takeover attempts; (4) Verify senders before clicking links - hover over email addresses, check for slight misspellings in domain names, legitimate companies use consistent domain patterns; (5) Backup important data offline weekly - ransomware increasingly targets cloud backups, so maintain one fully disconnected backup. Additional habits for Oct 2025: use VPNs on public WiFi, enable device encryption, lock screens immediately, and use biometric authentication. Studies show teams following these practices experience 78% fewer incidents than those without structured routines. India's DSCI (Data Security Council of India) recommends 15-minute security huddles weekly for teams.", author: "Hygiene Expert", tags: ["habits", "prevention", "daily"] },
  { id: 4, title: "Ransomware in 2025", category: "threats", date: "Sep 2025", readTime: "9 min", excerpt: "Modern ransomware tactics and comprehensive defense strategies.", content: "September 2025 threat intelligence reports show ransomware evolution has reached critical sophistication levels. Modern ransomware now employs triple-extortion tactics: encrypting files, exfiltrating data, and threatening to contact customers directly. LockBit 3.1, BlackCat (ALPHV), and Play ransomware variants dominate Q3 2025 attack campaigns. The average ransom demand in Sept 2025 is $2.4 million (up 156% from 2024), with attackers specifically targeting healthcare, finance, and manufacturing sectors. Comprehensive defense strategies include: (1) Detection systems - deploy EDR (Endpoint Detection & Response) with behavioral analytics, SIEM integration for rapid alerting; (2) Network segmentation - isolate critical systems, implement zero-trust architecture, use micro-segmentation with application-level controls; (3) Immutable backups - maintain 3-2-1 backup rule (3 copies, 2 media types, 1 offsite), test recovery monthly, use air-gapped backups never connected to network; (4) Incident response playbooks - define clear roles, communication templates, law enforcement contacts, define 2-hour containment target; (5) Threat intelligence subscription - monitor ransomware-as-a-service (RaaS) trends, track IOCs. Organizations in India should report incidents to CERT-In and consider cyber insurance. Recent case: A Delhi-based pharmaceutical company recovered from LockBit 3.1 in 48 hours using segmented networks and immutable backups, avoiding $5 million ransom. Expert consensus: Never pay ransoms as it funds future attacks.", author: "Response Team", tags: ["ransomware", "malware", "defense"] },
  { id: 5, title: "Zero Trust Architecture", category: "policy", date: "Nov 2025", readTime: "10 min", excerpt: "Transitioning from perimeter to continuous verification.", content: "November 2025 marks the inflection point where Zero Trust Architecture moves from aspirational to essential for enterprises. The perimeter-based security model is obsolete - 72% of breaches now occur within already-trusted networks. Zero Trust Architecture operates on three principles: (1) Never trust, always verify - treat every user and device as untrusted until proven otherwise; (2) Least privilege access - grant minimum permissions needed for specific task; (3) Continuous monitoring - verify authentication and authorization at each access attempt. Implementation roadmap for Nov 2025: Phase 1 (Months 1-3): Identity-centric security - implement SSO, MFA, passwordless authentication via Windows Hello or FIDO2 keys; Phase 2 (Months 4-6): Microsegmentation - segment networks into zones (data zones, user zones, device zones), enforce policies between zones; Phase 3 (Months 7-9): Continuous monitoring - deploy SIEM, behavioral analytics, EDR tools; Phase 4 (Months 10-12): Encryption everywhere - all data in transit (TLS 1.3) and at rest (AES-256). Key technologies: AWS IAM/Google Workspace for identity, Zscaler/Cloudflare for network, CrowdStrike/Microsoft Defender for endpoints. India's Ministry of Defence has mandated Zero Trust for all digital initiatives by end of 2025. Enterprise case study: A Bangalore-based tech company reduced breach risk by 94% after 8-month Zero Trust implementation, with initial investment of $1.2 million. NIST and India's DSCI recommend starting with sensitive data and expanding gradually to avoid implementation paralysis.", author: "Architecture", tags: ["zero-trust", "policy", "arch"] },
  { id: 6, title: "Cloud Security Best Practices", category: "policy", date: "Aug 2025", readTime: "7 min", excerpt: "Securing AWS, Azure, GCP with compliance and governance.", content: "August 2025 cloud security landscape shows 63% of enterprises now use multi-cloud strategies (AWS, Azure, GCP), creating complexity in security governance. Best practices for Aug 2025 include: (1) Native cloud tools - AWS Security Hub, Azure Defender, GCP Security Command Center provide centralized visibility; (2) Least privilege IAM - implement role-based access control (RBAC), use temporary credentials instead of long-lived keys, audit permissions monthly; (3) Encryption strategy - encrypt data in transit (TLS 1.3), at rest (server-side encryption enabled by default), and implement Key Management Service (KMS) for encryption keys; (4) Regular assessments - conduct cloud infrastructure assessments using AWS Config, Azure Policy, GCP Cloud Asset Inventory monthly, remediate misconfigurations within 48 hours; (5) Data localization - India's Data Protection law requires personal data stored within India, use region-locked storage; (6) Monthly audits - enable CloudTrail/Azure Activity Logs, retain logs for 90+ days, analyze for anomalies; (7) Credential rotation - rotate API keys, access tokens every 90 days; (8) Third-party management - vet cloud service providers, define SLAs, include security clauses; (9) Incident response - establish cloud-specific IR procedures for data exfiltration and account compromise. Red flags: unencrypted S3 buckets (source of 41% of data breaches), overly permissive security groups, default credentials. India's AWS Mumbai region and Azure India regions recommend compliance with DPDP Act 2023. Multi-cloud security tools: CloudSploit, Dome9, Orca provide unified monitoring across providers.", author: "Cloud Team", tags: ["cloud", "aws", "security"] },
  { id: 7, title: "API Security", category: "threats", date: "Jul 2025", readTime: "8 min", excerpt: "Securing REST and GraphQL APIs against attacks.", content: "July 2025 OWASP Top 10 (API 2023) identifies critical API vulnerabilities: (1) Broken Object Level Authorization (BOLA) - 61% of API breaches involve accessing resources without proper permission checks; (2) Injection attacks - SQL, NoSQL, command injection exploiting unvalidated inputs; (3) Broken Authentication - weak token validation, expired tokens accepted, JWT signature not verified; (4) Rate limiting failures - DDoS attacks exploiting unprotected APIs, average attacker sends 500+ requests/second; (5) Mass assignment - unintended fields modified by users; (6) Insufficient logging - breaches not detected for 200+ days. Security implementation for July 2025: (1) Input validation - whitelist allowed characters, use parameterized queries, validate data types and ranges; (2) OAuth 2.0 + OpenID Connect - industry-standard authentication, supports delegated access; (3) JWT token security - use RS256 algorithm (asymmetric), verify signature always, include 'exp' and 'iat' claims, rotate signing keys quarterly; (4) Rate limiting - implement token-bucket algorithm (e.g., 100 requests/minute/IP), use exponential backoff for retries; (5) Web Application Firewall (WAF) - AWS WAF, Cloudflare WAF block common attack patterns; (6) Encryption - TLS 1.3 for all API traffic, no HTTP allowed; (7) Regular pentesting - conduct API security assessments quarterly, use tools like Burp Suite, Postman security testing. GraphQL-specific concerns (July 2025): query complexity limits, introspection disabled in production, depth limiting to prevent recursive queries. India's NASSCOM published API Security guidelines in 2025 specifically for Indian enterprises. Monitoring: set up alerts for failed authentication (>5 attempts), rate limit breaches, unusual geographic access patterns.", author: "API Security", tags: ["api", "dev", "security"] },
  { id: 8, title: "Data Privacy & Governance", category: "policy", date: "Jun 2025", readTime: "7 min", excerpt: "Building governance aligned with privacy laws.", content: "June 2025 marks the full enforcement of India's Digital Personal Data Protection (DPDP) Act 2023. Organizations must implement comprehensive data governance frameworks. Implementation roadmap: (1) Data inventory - catalog all personal data, location (database/file), retention period, purpose, sensitivity level; (2) Privacy Impact Assessments (PIA) - conduct PIA for any new processing, high-risk processing, identify privacy risks and mitigation; (3) Retention policies - define data retention periods, auto-delete after retention expires, India DPDP mandates erasure within 30 days of consent withdrawal; (4) Access controls - least privilege, role-based access, audit logs for all access; (5) Breach procedures - maintain incident register, notify individuals within 72 hours of discovery, report to authority within 30 days; (6) Third-party management - vet vendors, ensure data processing agreements (DPA), audit vendors annually; (7) DPO appointment - designate Data Protection Officer, publish contact details, report to authority; (8) Consent management - maintain proof of consent, timestamp, consent duration, obtain fresh consent before June 2025. India-specific requirements: DPDP Act applies to organizations processing Indian residents' data globally. Sectoral regulations: RBI for financial data, MeitY for government, SEBI for capital markets. Penalties: ₹5 crore or 2% of turnover (whichever higher) for non-compliance. Best practices: encrypt personal data, anonymize data when possible, use privacy-by-design principles. Compliance tools: OneTrust, Truyo, TrustArc help manage DPDP compliance. Audit frequency: quarterly minimum, with third-party audit annually. Case study: Mumbai-based fintech company implemented full DPDP compliance in 4 months, affecting 2 million user records, cost ₹1.2 crore but avoided ₹50 crore potential penalty.", author: "Privacy Team", tags: ["privacy", "gdpr", "policy"] },
  { id: 9, title: "Threat Intelligence", category: "threats", date: "May 2025", readTime: "8 min", excerpt: "Collecting and operationalizing threat data.", content: "May 2025 threat landscape demands mature Threat Intelligence (TI) programs. TI lifecycle consists of: (1) Collection - sources include OSINT (Shodan, VirusTotal), commercial feeds (Mandiant, Recorded Future), ISACs (sectoral information sharing), dark web monitoring, SIEM logs, endpoints; (2) Analysis - contextualize indicators, identify patterns, assess impact and probability; (3) Dissemination - automated alerts for critical IOCs, tactical briefs for incident responders, strategic reports for executives; (4) Feedback - track remediation, measure TI effectiveness. TI types: Strategic (geopolitical trends, attacker motivations), Tactical (malware signatures, IOCs), Operational (attack campaigns, timelines). May 2025 recommendations: Subscribe to sector-specific threat feeds (e.g., financial sector: Cellebrite, healthcare: HHS), join ISACs (India has CERT-In, sectoral ISACs emerging), build internal TI teams with 1-2 analysts per 500 employees. Integration: feed IOCs into SIEM, firewall, endpoint detection systems with 2-hour update frequency. Threat hunting: establish hunting team, use MITRE ATT&CK framework, hunt for APT campaigns monthly, focus on indicators from past breaches. Emerging tools (May 2025): MISP (Malware Information Sharing Platform), Anomali ThreatStream, EclecticIQ automate TI collection. India-specific: CERT-In publishes 3-4 threat alerts daily, subscribe to mailing list, join India-ISAC. APT focus for May 2025: Lazarus targeting finance, APT41 targeting healthcare and tech, Wizard Spider (Conti) ransomware operations. TI ROI: organizations with mature TI programs detected breaches 40% faster than industry average.", author: "TI Team", tags: ["threat-intel", "ioc", "analysis"] },
  { id: 10, title: "Security Operations Center", category: "policy", date: "Apr 2025", readTime: "9 min", excerpt: "Establishing 24/7 SOCs for threat detection.", content: "April 2025 data shows organizations with SOCs detect and respond to incidents 40% faster, reducing breach impact by 60%. Establishing 24/7 SOC requires: (1) Structure - Tier 1 analysts monitor alerts (entry-level), Tier 2 analysts investigate incidents (3-5 years experience), Tier 3 responders handle complex incidents and strategic decisions (senior architects); (2) Core tools - SIEM (Splunk, Elastic, IBM QRadar) centralizes logs from firewalls, endpoints, servers; EDR (CrowdStrike, Microsoft Defender, SentinelOne) monitors endpoint behavior; threat feeds integrated with 30-minute updates; playbooks document response procedures; (3) Key metrics - MTTD (Mean Time To Detect) target <30 minutes for critical incidents, MTTR (Mean Time To Respond) target <2 hours for containment, Detection accuracy >95% to minimize false positives; (4) Staffing - 1 analyst per 500-1000 endpoints, 24/7 coverage requires 3 shifts minimum (3-4 analysts per shift); (5) Processes - incident triage (severity: critical/high/medium/low), escalation procedures, post-incident reviews, metrics dashboard for executives; (6) Red teaming - conduct exercises monthly simulating attacks, measure MTTD/MTTR, identify blind spots. April 2025 trend: managed SOCs (MSSP) growing, outsourced SOC services cost ₹50-100 lakhs monthly for mid-sized enterprises. India's CERT-In offers SOC readiness assessment. Setup timeline: 6-12 months from scratch, initial investment ₹1.5-3 crore. Tools ecosystem: SIEM (primary), SOAR (automation), vulnerability scanners, DNS security, email security. Case study: Delhi HQ bank established SOC in April 2025, reduced incident response time from 8 hours to 30 minutes, identified 45 threats in first month.", author: "SOC Ops", tags: ["soc", "siem", "ops"] }
];

async function seedBlogs() {
  try {
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Find the admin user
    const admin = await Admin.findOne({ username: 'admin' });
    if (!admin) {
      console.error('❌ Admin user not found. Please create admin first with: node scripts/create-admin.js');
      process.exit(1);
    }

    // Check how many blogs already exist
    const existingCount = await BlogSubmission.countDocuments();
    console.log(`📊 Existing blogs in database: ${existingCount}`);

    // Insert blogs
    let insertedCount = 0;
    for (const blog of existingBlogs) {
      // Check if blog already exists by title
      const exists = await BlogSubmission.findOne({ title: blog.title });
      
      if (!exists) {
        const newBlog = new BlogSubmission({
          title: blog.title,
          author: blog.author || 'HackHalt Team',
          category: blog.category || 'General',
          content: blog.content,
          excerpt: blog.excerpt,
          tags: blog.tags || [],
          adminId: admin._id,
          isPublished: true,
          viewCount: 0
        });

        await newBlog.save();
        insertedCount++;
        console.log(`✅ Added: ${blog.title}`);
      } else {
        console.log(`⏭️  Already exists: ${blog.title}`);
      }
    }

    console.log('');
    console.log(`🎉 Seed completed!`);
    console.log(`📝 Inserted: ${insertedCount} new blogs`);
    console.log(`📊 Total blogs now: ${existingCount + insertedCount}`);
    console.log('');
    console.log('✅ All blogs are now available in the admin panel at: http://localhost:5000/blog-admin');

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding blogs:');
    if (error.message.includes('querySrv')) {
      console.error('MongoDB connection failed. Check your MONGODB_URI in .env file.');
    } else {
      console.error(error.message);
    }
    process.exit(1);
  }
}

seedBlogs();
